fix(puppeteer): installation removed

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -8,45 +8,45 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "::set-output name=manager::yarn"
-            echo "::set-output name=command::install"
-            echo "::set-output name=runner::yarn"
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "::set-output name=manager::npm"
-            echo "::set-output name=command::ci"
-            echo "::set-output name=runner::npx --no-install"
-            exit 0
-          else
-            echo "Unable to determine packager manager"
-            exit 1
-          fi
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: "18"
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
-      - name: Restore cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            node_modules
-          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-          restore-keys: |
-            ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
-      - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-      - name: Install Chromium
-        run: node node_modules/puppeteer/install.js
-      - name: Type Check
-        run: ${{ steps.detect-package-manager.outputs.runner }} typecheck
-      - name: Build
-        env:
-          CI: false
-        run: ${{ steps.detect-package-manager.outputs.runner }} build
+    - name: Checkout
+      uses: actions/checkout@v4
+    - name: Detect package manager
+      id: detect-package-manager
+      run: |
+        if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+          echo "::set-output name=manager::yarn"
+          echo "::set-output name=command::install"
+          echo "::set-output name=runner::yarn"
+          exit 0
+        elif [ -f "${{ github.workspace }}/package.json" ]; then
+          echo "::set-output name=manager::npm"
+          echo "::set-output name=command::ci"
+          echo "::set-output name=runner::npx --no-install"
+          exit 0
+        else
+          echo "Unable to determine packager manager"
+          exit 1
+        fi
+    - name: Setup Node
+      uses: actions/setup-node@v4
+      with:
+        node-version: 20
+        cache: ${{ steps.detect-package-manager.outputs.manager }}
+    - name: Restore cache
+      uses: actions/cache@v4
+      with:
+        path: |
+          node_modules
+        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+        restore-keys: |
+          ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+    - name: Install dependencies
+      run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+    # - name: Install Chromium
+    #   run: node node_modules/puppeteer/install.js
+    - name: Type Check
+      run: ${{ steps.detect-package-manager.outputs.runner }} typecheck
+    - name: Build
+      env:
+        CI: false
+      run: ${{ steps.detect-package-manager.outputs.runner }} build
